version: '3.7'

services:
  asksdatabase:
    image: mysql
    container_name: asksdb_container
    environment:
      MYSQL_DATABASE: 'asksdb'
      MYSQL_ROOT_PASSWORD: 'asksdbpassword'
    volumes:
      - './database/:/var/lib/mysql'
    ports:
      - '9706:3306'
    networks:
      - backend
  asksapi:
    build: './api'
    container_name: asksapi_container
    volumes:
      - ./:/home/Documents/asks
    command: npm start
    ports:
      - '8080:8080'
    networks:
      - backend
networks:
  backend:
    driver: bridge